local_name: workbench.service.user # 本地服务名
k8s_service_name: workbench.user-be # k8s 服务名
runmode: debug                 # 开发模式, debug, release, test 部署时环境变量覆盖
jwt_secret: workbenchmuxihacker
tracing:
  jager: localhost:6831 # opentracing
db:  # DB 配置 部署时环境变量覆盖
  name: workbench_test
  addr:
  username:
  password:
auth_server:  # auth 内网
  host: pass.muxi-tech.xyz
  client_id:
  client_secret:
token:
  expired: 30 # 过期时间（天）
